# Generated by Django 4.0.1 on 2022-01-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sentence1', models.CharField(max_length=300)),
                ('Sentence2', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=1)),
                ('Pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DecWeb.pair')),
            ],
        ),
    ]
