# Generated by Django 4.0.1 on 2022-01-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DecWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='Sentence1',
            new_name='firstSentence',
        ),
        migrations.RenameField(
            model_name='pair',
            old_name='Sentence2',
            new_name='secondSentence',
        ),
    ]
